my_app/urls.py
from django.urls import path, include
from .router import router
from library_api import views

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.home, name="home"),
    path('writers/', views.writers, name="writers"),
]

mytest_project/urls.py
from django.urls import path, include
from .router import router
from library_api import views

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.home, name="home"),
    path('test/', views.test, name="test")
]

library_api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Writer(models.Model):
    places = [
        ('C', 'Colombia'),
        ('E', 'Ecuador'),
        ('V', 'Venezuela')
    ]
 
    name = models.CharField(max_length=50)
    nacionality = models.CharField(max_length=1, choices=places)
    death_date = models.DateField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(primary_key=True, max_length=100)
    writer = models.ManyToManyField(Writer)
    pages = models.PositiveIntegerField()
    language = models.CharField(max_length=20)
    editorial = models.CharField(max_length=100)

    def __str__(self):
        return self.title

library_api/views.py
from django.shortcuts import render
from .models import Book, Writer

def home(request):
    all_books = Book.objects.all
    return render(request, 'home.html', {'library': all_books})

def writers(request):
    all_writers = Writer.objects.all
    return render(request, 'writers.html', {'writers': all_writers})

library_api/templates/bootstrap_starter.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  <title>Library API</title>
</head>

<body><br /><br />
  <div class="container">
    {%block content%}
    {%endblock%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

library_api/templates/delete.html
{%extends 'bootstrap_starter.html' %}

{%block content%}

<p> El libro {{book.title}} será eliminado permanentemente </p>

<form methods="POST">
    <a href="{% url 'home'  %}">Cancel</a>
    <input type="submit" name="Confirm">
</form>

{%endblock%}

library_api/templates/home.html
{%extends 'bootstrap_starter.html' %}

{%block content%}

<div class="container">
    <div class="text-center my-3">
        <h2>LIBRARY</h2>
        <button type="button" class="btn btn-link" onclick="window.location.href='http://127.0.0.1:8000/writers/';">
            Check registered writers
        </button>
    </div>

    <div class="my-5">
        <div class="row justify-content-center mb-3">
            <div class="col-md-5 position-relative">
                <input class="form-control pl-3" style="padding-right: 2.5rem; border-radius: 5px;" id="searchInput"
                    type="text" placeholder="Search..." onkeyup="searchFunction()">
                <i class="fas fa-search position-absolute"
                    style="top: 50%; right: 25px; transform: translateY(-50%);"></i>
            </div>
        </div>

        <table id="booksTable" class="table table-bordered table-striped">
            <thead>
                <tr class="text-center">
                    <th>Name</th>
                    <th>Pages</th>
                    <th>Writer</th>
                    <th>Language</th>
                    <th>Editorial</th>
                    <th>Update</th>
                </tr>
            </thead>
            <tbody>
                {%for book in library%}
                <tr>
                    <td>{{book.title}}</td>
                    <td>{{book.pages}}</td>
                    <td>
                        <ul>
                            {%for writer in book.writer.all%}
                            <li>{{writer}}</li>
                            {%endfor%}
                        </ul>
                    </td>
                    <td>{{book.language}}</td>
                    <td>{{book.editorial}}</td>
                    <td onclick="editBook('{{book.title}}')" style="cursor: pointer" class="align-middle text-center"><i
                            class="fas fa-pen"></i>
                    </td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-end mb-3">
        <button type="button" class="btn btn-secondary"
            onclick="window.open('http://127.0.0.1:8000/api/book/', '_blank');">
            New book registration
        </button>
    </div>
</div>

<script>
    function searchFunction() {
        var input, filter, table, tr, td, i, j, txtValue;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("booksTable");
        tr = table.getElementsByTagName("tr");

        for (i = 0; i < tr.length; i++) {
            if (tr[i].getElementsByTagName("th").length > 0) {
                continue;
            }

            var found = false;
            for (j = 0; j < tr[i].cells.length; j++) {
                td = tr[i].cells[j];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        found = true;
                        break;
                    }
                }
            }
            if (found) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
        }
    }

    function editBook(title) {
        var url = "http://127.0.0.1:8000/api/book/" + title;
        window.open(url, '_blank');
    }
</script>

{%endblock%}

library_api/templates/writers.html
{%extends 'bootstrap_starter.html' %}

{%block content%}

<div class="container">
    <button type="button" class="btn btn-link" onclick="window.location.href='http://127.0.0.1:8000/';">
        <i class="fas fa-arrow-left mx-2"></i>
        Library
    </button>
    <div class="text-center my-3">
        <h2>Writers</h2>
    </div>

    <div class="my-5">
        <div class="row justify-content-center mb-3">
            <div class="col-md-5 position-relative">
                <input class="form-control pl-3" style="padding-right: 2.5rem; border-radius: 5px;" id="searchInput"
                    type="text" placeholder="Search..." onkeyup="searchFunction()">
                <i class="fas fa-search position-absolute"
                    style="top: 50%; right: 25px; transform: translateY(-50%);"></i>
            </div>
        </div>

        <table id="writersTable" class="table table-bordered table-striped">
            <thead>
                <tr class="text-center">
                    <th>Name</th>
                    <th>Nationality</th>
                    <th>Death date</th>
                    <th>Update</th>
                </tr>
            </thead>
            <tbody>
                {%for writer in writers%}
                <tr>
                    <td>{{writer.name}}</td>
                    <td>{{writer.get_nacionality_display}}</td>
                    <td>{{writer.death_date}}</td>
                    <td onclick="editWriter('{{writer.id}}')" style="cursor: pointer" class="align-middle text-center">
                        <i class="fas fa-pen"></i>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-end mb-3">
        <button type="button" class="btn btn-secondary"
            onclick="window.open('http://127.0.0.1:8000/api/writer/', '_blank');">
            New writer registration
        </button>
    </div>
</div>

<script>
    function searchFunction() {
        var input, filter, table, tr, td, i, j, txtValue;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("writersTable");
        tr = table.getElementsByTagName("tr");

        for (i = 0; i < tr.length; i++) {
            if (tr[i].getElementsByTagName("th").length > 0) {
                continue;
            }

            var found = false;
            for (j = 0; j < tr[i].cells.length; j++) {
                td = tr[i].cells[j];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        found = true;
                        break;
                    }
                }
            }
            if (found) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
        }
    }

    function editWriter(id) {
        var url = "http://127.0.0.1:8000/api/writer/" + id;
        window.open(url, '_blank');
    }
</script>

{%endblock%}